### ISSUE TITLE
missing support for HTTP authentication?

### ISSUE THREAD

**Issue by milianw** [ReverentEngineer/build-dashboard#8]
Hey,

it looks like one cannot use this when the ci server is behind a HTTP auth. I I try to run this with my companies buildbot host, I end up with this:

![Screenshot_20210630_203246](https://user-images.githubusercontent.com/57207/124013226-55c8ee80-d9e2-11eb-9b86-f3a0472aacb0.png)

I'm sorry for having to attach a screenshot, but my terminal is completely broken afterwards, I cannot select any text and even `stty sane` doesn't help to recover it :shrug: 

My hunch is that this fails because it tries to parse the HTTP auth site which is not a valid REST API response...

**Comment by ReverentEngineer** [comment]
Thanks. I just added HTTP auth support. If you installed from PyPI, the terminal weirdness might be resolved too.
